openapi: 3.0.3
info:
  title: Task CRUD API
  description: RESTful API for managing user-owned tasks with JWT authentication
  version: 1.0.0
  contact:
    name: Hackathon Todo Team

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.hackathon-todo.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/{user_id}/tasks:
    parameters:
      - $ref: '#/components/parameters/UserIdPath'

    get:
      summary: List user's tasks
      description: Retrieve a paginated list of tasks belonging to the authenticated user
      operationId: listTasks
      tags:
        - Tasks
      parameters:
        - name: page
          in: query
          description: Page number (1-indexed)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: status
          in: query
          description: Filter by task status
          required: false
          schema:
            $ref: '#/components/schemas/TaskStatus'
      responses:
        '200':
          description: Successful response with paginated task list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/{user_id}/tasks/{task_id}:
    parameters:
      - $ref: '#/components/parameters/UserIdPath'
      - $ref: '#/components/parameters/TaskIdPath'

    get:
      summary: Get a single task
      description: Retrieve a specific task by ID (must belong to authenticated user)
      operationId: getTask
      tags:
        - Tasks
      responses:
        '200':
          description: Successful response with task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Update a task
      description: Update an existing task (must belong to authenticated user)
      operationId: updateTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Delete a task
      description: Delete an existing task (must belong to authenticated user)
      operationId: deleteTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task deleted successfully
                  id:
                    type: string
                    format: uuid
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Better Auth

  parameters:
    UserIdPath:
      name: user_id
      in: path
      required: true
      description: User ID (must match authenticated user's ID from JWT)
      schema:
        type: string
        format: uuid

    TaskIdPath:
      name: task_id
      in: path
      required: true
      description: Task ID
      schema:
        type: string
        format: uuid

  schemas:
    TaskStatus:
      type: string
      enum:
        - pending
        - in_progress
        - completed
      description: Task status

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title
          example: Buy groceries
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description
          example: Milk, eggs, bread
        status:
          $ref: '#/components/schemas/TaskStatus'
          default: pending

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title
          example: Buy groceries and supplies
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description
          example: Milk, eggs, bread, coffee
        status:
          $ref: '#/components/schemas/TaskStatus'

    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Task unique identifier
          example: 550e8400-e29b-41d4-a716-446655440000
        user_id:
          type: string
          format: uuid
          description: Owner user ID
          example: 123e4567-e89b-12d3-a456-426614174000
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title
          example: Buy groceries
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description
          example: Milk, eggs, bread
        status:
          $ref: '#/components/schemas/TaskStatus'
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
          example: 2026-01-12T23:00:00Z
        updated_at:
          type: string
          format: date-time
          description: Last modification timestamp
          example: 2026-01-12T23:30:00Z

    TaskListResponse:
      type: object
      required:
        - items
        - total
        - page
        - page_size
        - total_pages
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Task'
          description: Array of tasks
        total:
          type: integer
          description: Total number of tasks
          example: 150
        page:
          type: integer
          description: Current page number
          example: 1
        page_size:
          type: integer
          description: Number of items per page
          example: 20
        total_pages:
          type: integer
          description: Total number of pages
          example: 8

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              description: Error code
              example: VALIDATION_ERROR
            message:
              type: string
              description: Human-readable error message
              example: Title is required and cannot be empty
            field:
              type: string
              description: Field name (for validation errors)
              example: title

  responses:
    BadRequest:
      description: Bad request - validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              code: VALIDATION_ERROR
              message: Title is required and cannot be empty
              field: title

    Unauthorized:
      description: Unauthorized - missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              code: UNAUTHORIZED
              message: Missing or invalid authentication token

    Forbidden:
      description: Forbidden - user_id mismatch or insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              code: FORBIDDEN
              message: You do not have permission to access this resource

    NotFound:
      description: Not found - task does not exist or does not belong to user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              code: NOT_FOUND
              message: Task not found or you do not have permission to access it

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              code: INTERNAL_ERROR
              message: An unexpected error occurred. Please try again later.
